service: desafio-service-gu

frameworkVersion: '3'

functions:
  handler:
    handler: src/01-presentation/app.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors: false
      - http:
          method: ANY
          path: /
          cors: false

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless/provider/environment.yml)}
  

custom: ${file(./serverless/custom/variables.yml)}

plugins:
 - serverless-esbuild
 - serverless-offline